/*
 * PORT_config.h
 *
 *  Created on: Feb 2, 2021
 *      Author: Hesham Adel
 */

#ifndef MCAL_DIO_PORT_CONFIG_H_
#define MCAL_DIO_PORT_CONFIG_H_

/*Choose :

 	 1-PORT_NOT_DEFINE
 	 2-PORT_DEFINE

 */

#define PORT_DEFINE

/*Choose :

  		   1- PORT_OUTPUT
		   2- PORT_INPUT

						                */

#define PORTA_PIN0_DIR		PORT_OUTPUT
#define PORTA_PIN1_DIR		PORT_OUTPUT
#define PORTA_PIN2_DIR		PORT_OUTPUT
#define PORTA_PIN3_DIR		PORT_OUTPUT
#define PORTA_PIN4_DIR		PORT_OUTPUT
#define PORTA_PIN5_DIR		PORT_OUTPUT
#define PORTA_PIN6_DIR		PORT_OUTPUT
#define PORTA_PIN7_DIR		PORT_OUTPUT

#define PORTB_PIN0_DIR		PORT_INPUT
#define PORTB_PIN1_DIR		PORT_INPUT
#define PORTB_PIN2_DIR		PORT_INPUT
#define PORTB_PIN3_DIR		PORT_INPUT
#define PORTB_PIN4_DIR		PORT_INPUT
#define PORTB_PIN5_DIR		PORT_INPUT
#define PORTB_PIN6_DIR		PORT_INPUT
#define PORTB_PIN7_DIR		PORT_INPUT

#define PORTC_PIN0_DIR		PORT_OUTPUT
#define PORTC_PIN1_DIR		PORT_OUTPUT
#define PORTC_PIN2_DIR		PORT_OUTPUT
#define PORTC_PIN3_DIR		PORT_OUTPUT
#define PORTC_PIN4_DIR		PORT_INPUT
#define PORTC_PIN5_DIR		PORT_INPUT
#define PORTC_PIN6_DIR		PORT_INPUT
#define PORTC_PIN7_DIR		PORT_INPUT

#define PORTD_PIN0_DIR		PORT_OUTPUT
#define PORTD_PIN1_DIR		PORT_OUTPUT
#define PORTD_PIN2_DIR		PORT_OUTPUT
#define PORTD_PIN3_DIR		PORT_OUTPUT
#define PORTD_PIN4_DIR		PORT_OUTPUT
#define PORTD_PIN5_DIR		PORT_OUTPUT
#define PORTD_PIN6_DIR		PORT_OUTPUT
#define PORTD_PIN7_DIR		PORT_OUTPUT

/*Choose :

 	 	In Output Mode :-

  		   1-PORT_HIGH For 5v
		   2-PORT_LOW  For 0v

		In Input Mode  :-

		   1-PORT_HIGH For PullUp
		   2-PORT_LOW  For Floating
						                */

#define PORTA_PIN0_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN1_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN2_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN3_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN4_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN5_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN6_INITIAL_VALUE		PORT_HIGH
#define PORTA_PIN7_INITIAL_VALUE		PORT_HIGH

#define PORTB_PIN0_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN1_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN2_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN3_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN4_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN5_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN6_INITIAL_VALUE		PORT_HIGH
#define PORTB_PIN7_INITIAL_VALUE		PORT_HIGH

#define PORTC_PIN0_INITIAL_VALUE		PORT_HIGH
#define PORTC_PIN1_INITIAL_VALUE		PORT_HIGH
#define PORTC_PIN2_INITIAL_VALUE		PORT_LOW
#define PORTC_PIN3_INITIAL_VALUE		PORT_LOW
#define PORTC_PIN4_INITIAL_VALUE		PORT_HIGH
#define PORTC_PIN5_INITIAL_VALUE		PORT_HIGH
#define PORTC_PIN6_INITIAL_VALUE		PORT_LOW
#define PORTC_PIN7_INITIAL_VALUE		PORT_LOW


#define PORTD_PIN0_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN1_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN2_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN3_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN4_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN5_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN6_INITIAL_VALUE		PORT_LOW
#define PORTD_PIN7_INITIAL_VALUE		PORT_LOW

#endif /* MCAL_DIO_PORT_CONFIG_H_ */
